### ISSUE TITLE
AI has no concept of stalemate

### ISSUE THREAD

**Issue by justingolden21** [zeyu2001/chess-ai#3] opened 2021-03-04 18:05 UTC
I can be heavily losing a game, and it will allow threefold repetition which results in a stalemate

It should evaluate stalemate as a score of 0

Just my two cents  : )

**Comment by huydhoang** [comment] 2021-08-31 06:21
> I can be heavily losing a game, and it will allow threefold repetition which results in a stalemate
> 
> It should evaluate stalemate as a score of 0
> 
> Just my two cents : )

It's a bug, it could not deliver checkmate. Refer to [my PR here](https://github.com/zeyu2001/chess-ai/pull/6).

**Comment by zeyu2001** [comment] 2021-08-31 09:53
Thanks @huydhoang. The issue is now fixed.

**Closed as completed by zeyu2001** 2021-08-31 09:53 UTC
